### ISSUE TITLE
Accept `weight` as a CLI parameter

### ISSUE THREAD

**Issue by batpad** [hotosm/ml-enabler-cli#7]
This `weight` should come in as a CLI parameter: https://github.com/hotosm/ml-enabler-cli/blob/master/ml_enabler/utils_postproc.py#L9

This should ideally be the area of one pixel in square metres, so that the model prediction is aggregated to sq m per tile. We should ideally allow the user to pass in a value of `auto`, in which case the size of each pixel would be calculated "on the fly" based on the latitude of the bounding box.

cc @wronk

**Comment by wronk** [comment]
Possible way to calculate pixel sizes for `auto` is outlined [here](https://github.com/hotosm/ml-enabler/issues/24) in the `ml-enabler` repo.
